version: '3'

services:
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=geccal_biblioteca_infatil
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - geccal-biblioteca-infantil-network

networks:
  geccal-biblioteca-infantil-network:
    driver: bridge